### ISSUE TITLE
"Element 'dfExtension': This element is not expected"

### ISSUE THREAD

**Issue by indunie** [mage2pro/securepay#6]
Hi,
I am getting the below error while installing to magento 2.4.
Could you please look into this.

The XML in file "/home/magento/ridgeline_m2/vendor/mage2pro/securepay/etc/  
  adminhtml/system.xml" is invalid:                                           
  Element 'dfExtension': This element is not expected.                        
  Line: 26                                                                    
                                                                              
  Verify the XML and try again.   

Thank you.

Regards,
Indunie Florence

**Comment by dmitrii-fediuk** [comment]
`dfExtension` is defined in the [`mage2/pro`](https://github.com/mage2pro/core) package which is installed by Composer automatically with the [`mage2pro/securepay`](https://github.com/mage2pro/securepay) package: https://github.com/mage2pro/securepay#2-self-installation

**Comment by dmitrii-fediuk** [comment]
Also, the issue could be related to https://github.com/mage2pro/core/issues/297
